version: 2.1

orbs:
  nix: eld/nix@1.1.1

jobs:
  build-arm64:
    machine:
      image: ubuntu-2404:current
    resource_class: arm.medium

    steps:
      - checkout

      - nix/install:
          extra-conf: |
            log-format = bar-with-logs
          logger: pretty

      - nix/install-cachix

      - nix/with-cachix:
          cachix-user: pydevrpi
          cache-name: pydevrpi
          nix-command: >-
            nix build --max-jobs auto --cores 0
            .#nixosConfigurations.rpi5.config.system.build.toplevel
            --accept-flake-config

workflows:
  build:
    jobs:
      - build-arm64:
          context:
            - cachix
          # filters:
          #   branches:
          #     only:
          #       - main
          #       - master
